project:
  type: website
  output-dir: docs

website:
  title: "ENVSOCTY 2GI3"
  favicon: "images/favicon.ico"
  sidebar:
    background: primary
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: materials.qmd
        text: Materials

format:
  html:
    theme: lux
    toc: false

execute:
  freeze: auto
